### ISSUE TITLE
Segmentation output format of Mask2Former does not match with segmentation masks of DEMON segmentation_masks for DECO code

### ISSUE THREAD

**Issue by dqj5182** [sha2nkt/deco#10]
Thanks for the answer.

After running the Mask2Former for semantic segmentation, the output segmentation does not seem to match with the segmentation_masks images for damon dataset (i.e., datasets/damon/segmentation_masks/training/vcoco_000000360328.png).

The segmentation maks for DAMON dataset is as follows:
![vcoco_000000360328](https://github.com/sha2nkt/deco/assets/56655511/376dbf49-8880-4159-afa5-4d7cd12b7077)

The segmentation output of Mask2Former is as follows:

**Comment by dqj5182** [comment]
![image](https://github.com/sha2nkt/deco/assets/56655511/234e4933-e857-4d01-b248-08579eda7eb0)

**Comment by ac5113** [comment]
You're most likely displaying the segmentation files as is. However, those arrays actually contain the class id in each pixel.
