### ISSUE TITLE
multiple-person image

### ISSUE THREAD

**Issue by linjing7** [sha2nkt/deco#13]
Hi, thanks for your great work! There exists some multi-person images in the HOT dataset. I'm wondering how could we know the annotated contact labels corresponding to which person?

**Comment by sha2nkt** [comment]
Hello, 

thanks a lot for your interest in our work! In this paper, we considered only single-person images and filtered out any multi-person images from HOT. This unfortunately means that the DAMON dataset does not include any annotation for multiperson images.

**Comment by linjing7** [comment]
Okay, thanks for your prompt response!
