### ISSUE TITLE
Visualization of the scene segmentation maps

### ISSUE THREAD

**Issue by ChrisChenYh** [sha2nkt/deco#14]
Thanks for your sharing.
I visualize the scene segmentation maps predicted by the model './checkpoints/Release_Checkpoint/deco_best.pth', but I find that the results seem weird, as shown in the picture, there are many wrong categories. I wonder if you could give some advice.  Here is the code, which is mainly borrowed from mask2former.
![image](https://github.com/sha2nkt/deco/assets/145037668/f109f8e4-4fc0-4290-871a-4284c33faa53)
![image](https://github.com/sha2nkt/deco/assets/145037668/62d074ad-452b-46cd-bb49-9203d3dcd67d)

**Comment by sha2nkt** [comment]
This is expected. The scene segmentation branch in DECO is only meant to add semantic context about the scene to help DECO reason about contact. It is not supposed to work well as a segmentation model.
