### ISSUE TITLE
About smpl_2_smplx.pkl

### ISSUE THREAD

**Issue by yyvhang** [sha2nkt/deco#17]
Hi, thanks for the work, I want to know where can I get the smpl_2_smplx.pkl in [here](https://github.com/sha2nkt/deco/blob/f592cb226bcf1797c0700ad0925f57f5357cc6ed/reformat_contacts.py#L37). It seems not in the download dataset.

**Comment by ac5113** [comment]
You need to download the utility files for deco (which contains these pkl files), by using [this](https://github.com/sha2nkt/deco/blob/main/fetch_data.sh) script.

**Comment by yyvhang** [comment]
thanks for your reply, I have another question, is there any file like `smpl_neutral_geodesic_dist.npy ` for smplx? So that we can compute the `geo. (cm) ` for smplx contact estimation.

**Comment by ac5113** [comment]
This file was obtained from the [RICH website](https://rich.is.tue.mpg.de/), which only contains the SMPL geodesic distances.
Perhaps, something like [this](https://github.com/mikedh/trimesh/issues/955), could be used for SMPL-X, to create such a file.
