### ISSUE TITLE
geodesic_dist for smplx

### ISSUE THREAD

**Issue by yyvhang** [sha2nkt/deco#18]
Hi, is there any file like `smpl_neutral_geodesic_dist.npy` for smplx? So that we can compute the `geo. (cm)`  for smplx contact estimation.

**Comment by ac5113** [comment]
Since the RICH website (which was the source of the original file) did not contain the SMPL-X version, perhaps it could be generated by [this method](https://github.com/mikedh/trimesh/issues/955).
