### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by doris-hash** [sha2nkt/deco#19]
Hi, your work is good. There is no checkpoints folder, where to download the checkpoints

**Comment by ac5113** [comment]
Hello, you have to run the shell script, as explained [here](https://github.com/sha2nkt/deco#installation-and-setup), to download the checkpoints. [This line](https://github.com/sha2nkt/deco/blob/f592cb226bcf1797c0700ad0925f57f5357cc6ed/fetch_data.sh#L10) in the script downloads all the necessary checkpoints, which can be found in the `checkpoints` directory.
