### ISSUE TITLE
UV map of contact extraction

### ISSUE THREAD

**Issue by antonagafonov** [sha2nkt/deco#2]
Hi,
Until now I only ran the inference.py , and got some results, a great and useful paper.

I am wondering, were I need to edit your code to get the UV map of contact.

Thanks

AA

**Comment by sha2nkt** [comment]
DECO outputs contact as 6890 per-vertex labels on the SMPL template mesh. You can use these labels along with the SMPL/SMPL-X UV maps provided by the [SMPL](https://smpl.is.tue.mpg.de/download.php)/[SMPL-X](https://smplx.is.tue.mpg.de/download.php) website along with the vertex labels from DECO to get colored UV maps for contact. Currently, we don't support this feature in the DECO repository but feel free to open a PR.
