### ISSUE TITLE
Data files regarding "test_chore_phosa.py"

### ISSUE THREAD

**Issue by dqj5182** [sha2nkt/deco#5]
May I ask you to provide data files (i.e., hot_behave_test_reduced.npz) in "test_chore_phosa.py" script?

**Comment by sha2nkt** [comment]
This script is spurious and we plan to remove it from the code release. For testing DECO, please use the following instructions. 
https://github.com/sha2nkt/deco/tree/e0ba8a4d03387107a2dfe5eeac2c3586aee0348d#evaluation
