### ISSUE TITLE
About loading DAMON dataset to DECO code

### ISSUE THREAD

**Issue by dqj5182** [sha2nkt/deco#8]
I have successfully downloaded the DAMON dataset and its images. However, the directory names do not match with each other.
The downloaded images are in HOT-Annotated/images, but the code is based on HOT/Contact_Data/images/training.
Could you solve this issue?

![Screen Shot 2023-10-12 at 6 03 08 PM](https://github.com/sha2nkt/deco/assets/56655511/a5c04e35-5cbb-4f36-aa9d-92fa11ec7b4d)

<img width="715" alt="Screen Shot 2023-10-12 at 6 03 28 PM" src="https://github.com/sha2nkt/deco/assets/56655511/77517343-2aef-4653-b9b4-83319f3d8a27">

**Comment by sha2nkt** [comment]
This issue was resolved in the new updated DAMON npzs. Please let us know if you are still facing this.

**Comment by EnnaSachdeva** [comment]
@dqj5182 were you able to train the model with the updated DAMON npzs?I still face the same issue as I mentioned [here](https://github.com/sha2nkt/deco/issues/16).

**Comment by dqj5182** [comment]
@EnnaSachdeva Hi! Honestly, I haven't checked for DAMON after the update. But, the process of "Training on custom datasets" seemed to be working fine for me (also not for DAMON btw).

**Comment by EnnaSachdeva** [comment]
@dqj5182 , Thanks for the information.
@sha2nkt , could you please look into this issue?
