### ISSUE TITLE
What version of Mask2Former was used for extracting scene segmentation?

### ISSUE THREAD

**Issue by dqj5182** [sha2nkt/deco#9]
Which Mask2Former pretrained checkpoint did the paper use to conduct scene segmentation? (among https://github.com/facebookresearch/Mask2Former/blob/main/MODEL_ZOO.md)

Was it custom trained and tested on the DECO, RICH, PROX dataset? or was it pretrained models of segmentation dataset (i.e., Cityscape)?

**Comment by ac5113** [comment]
A pretrained model was used. More specifically, this [config](https://github.com/facebookresearch/Mask2Former/blob/main/configs/coco/panoptic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_100ep.yaml).

**Comment by dqj5182** [comment]
Thanks for the answer.

After running the Mask2Former for semantic segmentation, the output segmentation does not seem to match with the segmentation_masks images for damon dataset (i.e., datasets/damon/segmentation_masks/training/vcoco_000000360328.png).

The segmentation maks for DAMON dataset is as follows:
![vcoco_000000360328](https://github.com/sha2nkt/deco/assets/56655511/ddaf9c34-076e-438a-8024-237db36a9048)

The segmentation output of Mask2Former on BEHAVE dataset is as follows:
![image](https://github.com/sha2nkt/deco/assets/56655511/796530e7-8a8b-4e23-b9c4-32f721311c16)
